name: CI Workflow

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.7

      - name: Download poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies with poetry
        run: poetry install

      - name: Run pytest
        run: poetry run pytest -v
